hotel/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('installation/',include('installation.urls')),
    path('panel/', include('panel.urls')),
    path('', include('manager.urls')),
]

if not settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
	urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

handler400 ='errors.views.error_400'
handler403 ='errors.views.error_403'
handler404 ='errors.views.error_404'
handler500='errors.views.error_500'

panel/urls.py
from django.urls import path
from django import views
from . import views
from .views import *
from .forms import UserResetPassword
from django.contrib.auth import views as auth_views
urlpatterns=[
    path('',views.dashboard,name='admin dashboard'),
    path('accounts/logout',views.user_logout,name='logout'),
    path('site/settings',SiteSettings.as_view(),name='site settings'),
    path('edit/card/<str:cardid>',Editcard.as_view(),name='edit card'),
    path('site/contact',views.siteContact,name='site contact'),
    path('view/cards',views.cards,name='view cards'),
    path('delete/card/<str:cardid>',views.DeleteCard,name='delete card'),
    path('site/working/days',views.siteWorking,name='site working days'),
    path('site/social/links',views.siteSocial,name='site social links'),
    path('accounts/login',LoginView.as_view(),name='login'),
    path('site/card/config',CardConfig.as_view(),name='card config'),
    path('accounts/reset/password',auth_views.PasswordResetView.as_view(form_class=UserResetPassword,template_name='panel/password_reset.html'),name='reset_password'),
    path('accounts/password/reset/link/sent',auth_views.PasswordResetDoneView.as_view(template_name='panel/password_reset_done.html'),name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='panel/password_reset_confirm.html'),name='password_reset_confirm'),
    path('accounts/password/reset/complete',auth_views.PasswordResetCompleteView.as_view(template_name='panel/password_reset_complete.html'),name='password_reset_complete'),
    path('site/admins',views.admins,name='site admins'),
    path('site/add/admins',AddAdmins.as_view(),name='add admins'),
    path('delete/loan/item/<str:loanid>',views.delLoan,name='delete loan'),
    path('site/edit/admin/<int:id>',EditAdmin.as_view(),name='edit admin'),
    path('site/delete/admin/<int:id>',views.deleteAdmin,name='delete admin'),
    path('site/employees',views.employees,name='site employees'),
    path('site/add/employee',AddEmployees.as_view(),name='add employees'),
    path('edit/loan/item/<str:loanid>',Editloan.as_view(),name='edit loan'),
    path('site/edit/employee/<int:id>',EditEmployee.as_view(),name='edit employee'),
    path('site/delete/employee/<int:id>',views.deleteEmployee,name='delete employee'),
    path('user/change/password',views.passwordChange,name='change password'),
    path('user/profile/pic',views.profilePic,name='profile pic'),
    path('<str:username>',ProfilerView.as_view(),name='profile'),
    path('loan/applications',views.applications,name='franchise applications'),
    path('customers/queries',views.queries,name='customers queries'),
    path('edit/query/<int:id>',EditQuery.as_view(),name='edit query'),
    path('delete/query/<int:id>',views.deleteQuery,name='delete query'),
    path('customer/suggestions',views.suggestions,name='customer suggestions'),
    path('delete/customer/suggestion/<int:id>',views.deleteSuggestion,name='delete suggestion'),
    path('customer/contact/messages',views.customerMessages,name='customers contacts'),
    path('view/message/<int:id>',ViewMessage.as_view(),name='view message'),


]

installation/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from django.utils.timezone import now
import environ
env=environ.Env()
environ.Env.read_env()

# Create your models here.

class SiteConstants(models.Model):
    user=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    site_name=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_NAME'))
    site_email=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_EMAIL'))
    site_email2=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_EMAIL2'))
    theme_color=models.CharField(null=True,blank=True,max_length=100,default=env('THEME_COLOR'))
    site_url=models.URLField(null=True,blank=True,default=env('SITE_URL'))
    description=models.TextField(null=True,blank=True,default=env('SITE_DESCRIPTION'))
    key_words=models.TextField(null=True,blank=True,default=env('SITE_KEYWORDS'))
    address=models.CharField(null=True,blank=True,max_length=250,default=env('SITE_ADDRESS'))
    location=models.CharField(null=True,blank=True,max_length=250,default=env('SITE_LOCATION'))
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',unique=False,default=env('SITE_PHONE1'))
    working_days=models.CharField(null=True,blank=True,max_length=250,default="mon-fri")
    site_content=models.CharField(null=True,blank=True,max_length=250)
    working_hours=models.CharField(null=True,blank=True,max_length=250,default="8am-10pm")
    closed_days=models.CharField(null=True,blank=True,max_length=250,default="sun")
    special_days=models.CharField(null=True,blank=True,max_length=250,default="sat & holidays")
    special_hours=models.CharField(null=True,blank=True,max_length=250,default="sat & holidays")
    facebook=models.URLField(null=True,blank=True,max_length=250,default=env('FACEBOOK_LINK'))
    twitter=models.URLField(null=True,blank=True,max_length=250,default=env('TWITTER_LINK'))
    instagram=models.URLField(null=True,blank=True,max_length=250,default=env('INSTAGRAM_LINK'))
    whatsapp=models.URLField(null=True,blank=True,max_length=250,default=env('WHATSAPP_LINK'))
    linkedin=models.URLField(null=True,blank=True,max_length=250,default=env('LINKEDIN_LINK'))
    youtube=models.URLField(null=True,blank=True,max_length=250,default=env('YOUTUBE_LINK'))
    favicon=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon.ico")
    icon_180=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-180x180.png")
    icon_32=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-32x32.png")
    icon_16=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-16x16.png")
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='site_constants'
        verbose_name_plural='site_constants'
    def __str__(self):
        return f'{self.user.username} site constants'

panel/models.py
from django.db import models

# Create your models here.

panel/forms.py
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from .models import *
from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.forms import User
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.contrib.auth.hashers import check_password
from django.core.validators import FileExtensionValidator,URLValidator
from installation.models import SiteConstants
import re
from urllib.parse import urlparse
from manager.models import ExtendedAuthUser
from manager.models import RequestModel,ContactModel,LoanModel,CardModel

class UserResetPassword(PasswordResetForm):
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter email address'}),error_messages={'required':'Email address is required'})

    def clean_email(self):
        email=self.cleaned_data['email']
        if  not User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email address does not exist')
        try:
            validate_email(email)
        except ValidationError:
            raise forms.ValidationError('Invalid email address')
        return email


class SiteForm(forms.ModelForm):
    site_name=forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Site name'}),error_messages={'required':'Site Name is required'})
    description=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Site Description'}),error_messages={'required':'Site Description is required'})
    theme_color=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Site Theme Color eg #ff0000'}),required=False)
    key_words=forms.CharField(widget=forms.TextInput(attrs={'data-role':'tagsinput','class':'bs-input','placeholder':'Site Keywords'}),required=False)
    site_url=forms.URLField(widget=forms.URLInput(attrs={'class':'form-control','placeholder':'Site URL'}),error_messages={'required':'Site URL is required'})
    favicon=forms.ImageField(
                                widget=forms.FileInput(attrs={'class':'custom-file-input','id':'customFileInput','accept':'image/*','hidden':True}),
                                required=False,
                                validators=[FileExtensionValidator(['jpg','jpeg','png','ico'],message="Invalid image extension",code="invalid_extension")]
                                )
    class Meta:
        model=SiteConstants
        fields=['site_name','theme_color','site_url','description','key_words','favicon',]
    
            
    def clean_theme_color(self):
        theme_color=self.cleaned_data['theme_color']
        match=re.search(r'^#(?:[0-9a-fA-F]{1,2}){3}$',theme_color)
        if not match:
            raise forms.ValidationError('Invalid color code given')
        else:
            return theme_color
            
    def clean_site_url(self):
        site_url=self.cleaned_data['site_url']
        if URLValidator(site_url):
            return site_url
        else:
            raise forms.ValidationError('Invalid url')

#AddressConfigForm
class AddressConfigForm(forms.ModelForm):
    site_email=forms.EmailField(widget=forms.EmailInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Site Email Address'}),error_messages={'required':'Address is required'})
    site_email2=forms.EmailField(widget=forms.EmailInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Site Additional Email Address'}),required=False)
    address=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:lowercase;','class':'form-control'}),error_messages={'required':'Address is required'})
    location=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:lowercase;','class':'form-control'}),error_messages={'required':'Location is required'})
    phone=PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'style':'text-transform:lowercase;','class':'form-control'},initial='KE'),required=False)
    class Meta:
        model=SiteConstants
        fields=['address','location','phone','site_email','site_email2']
    
    def clean_site_email(self):
        email=self.cleaned_data['site_email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('A user with this email already exists.')
        try:
            validate_email(email)
        except ValidationError as e:
            raise forms.ValidationError('Invalid email address.')
        return email
    
    def clean_site_email2(self):
        email=self.cleaned_data['site_email2']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('A user with this email already exists.')
        try:
            validate_email(email)
        except ValidationError as e:
            raise forms.ValidationError('Invalid email address.')
        return email


#social form
class UserSocialForm(forms.ModelForm):
    facebook=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Facebook Link'}),required=False)    
    twitter=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Twitter Link'}),required=False)    
    github=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Github Link'}),required=False)  
    instagram=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Instagram Link'}),required=False)    
    linkedin=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Linkedin Link'}),required=False)   
    youtube=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Youtube Link'}),required=False)    
    whatsapp=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','class':'form-control','placeholder':'Whats App'}),required=False)
    class Meta:
        model=SiteConstants
        fields=['facebook','twitter','linkedin','instagram','whatsapp','youtube','github',]

    def clean_facebook(self):
        facebook=self.cleaned_data['facebook']
        if URLValidator(facebook):
                output=urlparse(facebook)
                username=output.path.strip('/')
                if not username:
                    raise forms.ValidationError('Username parameter missing')
                else:
                    return [facebook,username]
        else:
            raise forms.ValidationError('Invalid url')
    
    def clean_twitter(self):
        twitter=self.cleaned_data['twitter']
        if URLValidator(twitter):
                output=urlparse(twitter)
                username=output.path.strip('/')
                if not username:
                    raise forms.ValidationError('Username parameter missing')
                else:
                    return [twitter,username]
        else:
            raise forms.ValidationError('Invalid url')
    

    def clean_github(self):
        github=self.cleaned_data['github']
        if URLValidator(github):
                output=urlparse(github)
                username=output.path.strip('/')
                if not username:
                    raise forms.ValidationError('Username parameter missing')
                else:
                    return [github,username]
        else:
            raise forms.ValidationError('Invalid url')
    def clean_instagram(self):
        instagram=self.cleaned_data['instagram']
        if URLValidator(instagram):
                output=urlparse(instagram)
                username=output.path.strip('/')
                if not username:
                    raise forms.ValidationError('Username parameter missing')
                else:
                    return [instagram,username]
        else:
            raise forms.ValidationError('Invalid url')
    
    def clean_linkedin(self):
        linkedin=self.cleaned_data['linkedin']
        if URLValidator(linkedin):
                output=urlparse(linkedin)
                username=output.path.strip('/')
                if not username:
                    raise forms.ValidationError('Username parameter missing')
                else:
                    return [linkedin,username]
        else:
            raise forms.ValidationError('Invalid url')
    
    def clean_youtube(self):
        youtube=self.cleaned_data['youtube']
        if URLValidator(youtube):
                output=urlparse(youtube)
                username=output.path.strip('/')
                if not username:
                    raise forms.ValidationError('Channel id parameter missing')
                else:
                    return [youtube,username]
        else:
            raise forms.ValidationError('Invalid url')
    def clean_whatsapp(self):
        whatsapp=self.cleaned_data['whatsapp']
        if URLValidator(whatsapp):
            output=urlparse(whatsapp)
            username=output.path.strip('/')
            if not username:
                raise forms.ValidationError('username parameter missing')
            else:
                return [whatsapp,username]
        else:
            raise forms.ValidationError('Invalid url')

#WorkingConfigForm
class WorkingConfigForm(forms.ModelForm):
    working_days=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:lowercase;','class':'form-control'}),error_messages={'required':'Working days is required'})

templates/panel/edit_admin.html
{% extends 'panel/base.html' %}
{% load static %}
{% block body %}
 <div class="container-fluid">
    <div class="row">
        <div class="col-md-12 m-b-30">
            <!-- begin page title -->
            <div class="d-block d-sm-flex flex-nowrap align-items-center">
                <div class="page-title mb-2 mb-sm-0">
                    <h1>Edit Admin</h1>
                </div>
                <div class="ml-auto d-flex align-items-center">
                    <nav>
                        <ol class="breadcrumb p-0 m-b-0">
                            <li class="breadcrumb-item">
                                <a  href="{% url 'admin dashboard' %}"><i class="ti ti-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'admin dashboard' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'site admins' %}">View admins</a>
                            </li>
                            <li class="breadcrumb-item active text-primary" aria-current="page">Edit {{admin.get_full_name}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- end page title -->
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 mx-auto">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title text-capitalize">{{admin.get_full_name }} Details</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="RegForm" method="post" action="{% url 'edit admin' id=admin.id %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">               
                            <label for="id_theme_color">Profile pic</label>
                            <div class="custom-file" style="cursor:pointer">
                                {{form1.profile_pic}}
                                <label for="customFileInput" class="custom-file-label">Browse files</label>
                            </div>
                            current: <a class="text-pimary" href="/media/logos{{admin.extendedauthuser.profile_pic.url}}">{{admin.extendedauthuser.profile_pic}}</a>
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_first_name">First Name</label>
                            {{form1.first_name}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_last_name">Last Name</label>
                            {{form1.last_name}}
                            <div class="feedback"></div>
                        </div>
                       
                        <div class="form-group">               
                            <label for="id_email">Email</label>
                            {{form1.email}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Username</label>
                            {{form1.username}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_username">Role</label>
                            {{form2.role}}
                            <div class="feedback"></div>
                        </div>
                        <label for="id_phone">Phone</label>
                        <div class="form-group">               
                            {{form2.phone}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center" style="margin-top:60px">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>  
    </div>
 </div>
{% endblock %}

templates/panel/site_settings.html
{% extends 'panel/base.html' %}
{% load static %}
{% block body %}
 <div class="container-fluid">
    <div class="row">
        <div class="col-md-12 m-b-30">
            <!-- begin page title -->
            <div class="d-block d-sm-flex flex-nowrap align-items-center">
                <div class="page-title mb-2 mb-sm-0">
                    <h1>Site Settings</h1>
                </div>
                <div class="ml-auto d-flex align-items-center">
                    <nav>
                        <ol class="breadcrumb p-0 m-b-0">
                            <li class="breadcrumb-item">
                                <a  href="{% url 'admin dashboard' %}"><i class="ti ti-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{% url 'admin dashboard' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item active text-primary" aria-current="page">Site Settings</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- end page title -->
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title">Site Details</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="EditForm" method="post" action="{% url 'site settings' %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_site_name">Site Name</label>
                            {{form1.site_name}}
                            <div class="feedback"></div>
                        </div>
                        <div class="selects-contant-boots">
                            <div class="form-group bs-select-1">               
                                <label for="id_key_words">Site Key Words</label>
                                {{form1.key_words}}
                                <div class="feedback"></div>
                            </div>
                        </div>
                        <div class="form-group">               
                            <label for="id_site_url">Site URL</label>
                            {{form1.site_url}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_theme_color">Site Theme Color</label>
                            {{form1.theme_color}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_theme_color">Favicon</label>
                            <div class="custom-file" style="cursor:pointer">
                                {{form1.favicon}}
                                <label for="customFileInput" class="custom-file-label">Browse files</label>
                            </div>
                            current: <a class="text-pimary" href="/media/logos/{{obj.favicon.url}}">{{obj.favicon}}</a>
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">
                            <label for="id_description">Description</label>
                            {{form1.description}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title">Contact information</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="EditForm" method="post" action="{% url 'site contact' %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_site_name">Site Email Address</label>
                            {{form2.site_email}}
                            <div class="feedback"></div>
                        </div>
                        <div class="selects-contant-boots">
                            <div class="form-group bs-select-1">               
                                <label for="id_key_words">Additional Site Email Address</label>
                                {{form2.site_email2}}
                                <div class="feedback"></div>
                            </div>
                        </div>
                        <div class="form-group">               
                            <label for="id_location">Site location</label>
                            {{form2.location}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_address">Site Address</label>
                            {{form2.address}}
                            <div class="feedback"></div>
                        </div>

                        <label for="id_phone">Site Phone</label>
                        <div class="form-group">               
                            {{form2.phone}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center" style="margin-top:67px">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title">Working Days And Hours</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="EditForm" method="post" action="{% url 'site working days' %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_working_days">Site Working Days</label>
                            {{form4.working_days}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_working_hours">Site Working Hours</label>
                            {{form4.working_hours}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title">Site Social Links</h4>
                    </div>
                </div>
                <div class="card-body"> 
                    <form class="EditForm" method="post" action="{% url 'site social links' %}" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_facebook">Facebook</label>
                            {{form3.facebook}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_twitter">Twitter</label>
                            {{form3.twitter}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_instagram">Instagram</label>
                            {{form3.instagram}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_linkedin">Linkedin</label>
                            {{form3.linkedin}}
                            <div class="feedback"></div>
                        </div>
                         <div class="form-group">               
                            <label for="id_whatsapp">Whatsapp</label>
                            {{form3.whatsapp}}
                            <div class="feedback"></div>
                        </div>
                        <div class="form-group">               
                            <label for="id_youtube">Youtube</label>
                            {{form3.youtube}}
                            <div class="feedback"></div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">
                                <span></span><span>submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}